spring:
  ai:
    mcp:
      server:
        name: yu-image-search-mcp-server
        version: 0.0.1
#        type: ASYNC
        # sse
        stdio: false
        sse-endpoint: /sse

  main:
    web-application-type: reactive
    banner-mode: off
