spring:
  ai:
    mcp:
      server:
        name: alarm-mcp-server
        version: 0.0.1
        # type: ASYNC
        # sse
        stdio: false
        sse-endpoint: /sse


  data:
    mongodb:
      host: 100.80.6.214
      port: 27017
      database: test
      username: root
      password: Zhywgl0411
      authentication-database: admin


  main:
    web-application-type: servlet
    banner-mode: off
