spring:
  ai:
    mcp:
      server:
        name: alarm-mcp-server
        version: 0.0.1
        type: ASYNC
        # stdio
        stdio: true
  # stdio
  main:
    web-application-type: none
    banner-mode: off